# PostgreSQL Database Configuration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: ev-infra
data:
  init-db.sql: |
    CREATE DATABASE evsaas_db;
    GRANT ALL PRIVILEGES ON DATABASE evsaas_db TO evsaas;
    
    CREATE DATABASE notification_db;
    GRANT ALL PRIVILEGES ON DATABASE notification_db TO evsaas;
    
    CREATE DATABASE evsaas_timeseries_db;
    GRANT ALL PRIVILEGES ON DATABASE evsaas_timeseries_db TO evsaas;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ev-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "evsaas"
        - name: POSTGRES_PASSWORD
          value: "evsaas_password"
        - name: POSTGRES_DB
          value: "postgres"
        volumeMounts:
        - name: postgres-init-scripts
          mountPath: /docker-entrypoint-initdb.d
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-init-scripts
        configMap:
          name: postgres-init-scripts
      - name: postgres-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ev-infra
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
