version: '3.8'

services:
  ## Database
  postgres:
    image: timescale/timescaledb-postgis:latest-pg13
    container_name: ev-saas-postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: evsaas
      POSTGRES_PASSWORD: evsaas_password
      POSTGRES_DB: evsaas_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - ev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U evsaas"]
      interval: 10s
      timeout: 5s
      retries: 5

  ## Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: ev-saas-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - ev-network
    command: redis-server --save 60 1 --loglevel warning

  ## Service Discovery
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: ev-saas-eureka
    ports:
      - "8761:8761"
    networks:
      - ev-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  ## API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: ev-saas-gateway
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - ev-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

volumes:
  postgres_data:
  redis_data:

networks:
  ev-network:
    driver: bridge 