# Direct Service Proxy Configuration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-proxy
  namespace: ev-saas
  labels:
    app: service-proxy
    component: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-proxy
  template:
    metadata:
      labels:
        app: service-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: service-proxy-conf
---
apiVersion: v1
kind: Service
metadata:
  name: service-proxy
  namespace: ev-saas
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30090
  selector:
    app: service-proxy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-proxy-conf
  namespace: ev-saas
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        
        # Root endpoint with service list
        location = / {
            return 200 'EV SaaS Services Proxy\n\nAvailable services:\n- /auth/\n- /billing/\n- /notifications/\n- /roaming/\n- /stations/\n- /scheduler/\n- /smart-charging/\n- /users/\n- /eureka/\n';
            add_header Content-Type text/plain;
        }
        
        # Health check endpoint
        location = /health {
            default_type application/json;
            return 200 '{"status":"UP","services":[{"name":"service-proxy","status":"UP"}]}';
        }
        
        # Service routing
        location /auth/ {
            proxy_pass http://auth-service.ev-saas.svc.cluster.local:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /billing/ {
            proxy_pass http://billing-service.ev-saas.svc.cluster.local:8083/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 60s;
        }
        
        location /notifications/ {
            proxy_pass http://notification-service.ev-saas.svc.cluster.local:8087/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /roaming/ {
            proxy_pass http://roaming-service.ev-saas.svc.cluster.local:8088/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /stations/ {
            proxy_pass http://station-service.ev-saas.svc.cluster.local:8084/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /scheduler/ {
            proxy_pass http://scheduler-service.ev-saas.svc.cluster.local:8085/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /smart-charging/ {
            proxy_pass http://smart-charging-service.ev-saas.svc.cluster.local:8086/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /users/ {
            proxy_pass http://user-service.ev-saas.svc.cluster.local:8082/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /eureka/ {
            proxy_pass http://eureka-server.ev-saas.svc.cluster.local:8761/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
