server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/log/containers/*.log
    pipeline_stages:
      - docker: {}
      - regex:
          expression: '(?P<service>.*?)_.*'
      - labels:
          service:

  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log

  - job_name: services
    static_configs:
      - targets:
          - localhost
        labels:
          job: ev-saas-services
          __path__: /var/log/ev-services/*.log 