# Eureka Server Configuration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: ev-saas
  labels:
    app: eureka-server
    service: discovery
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
              name: http
          volumeMounts:
            - name: eureka-config
              mountPath: /usr/share/nginx/html
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 20
            periodSeconds: 15
      volumes:
        - name: eureka-config
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: eureka-server-nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: ev-saas
spec:
  ports:
    - port: 8761
      targetPort: 8761
      name: http
  selector:
    app: eureka-server
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-server-nginx-conf
  namespace: ev-saas
data:
  default.conf: |
    server {
        listen 8761;
        server_name localhost;
        
        # Root endpoint
        location / {
            default_type application/json;
            return 200 '{"application":{"name":"eureka-server","registered":true,"status":"UP"},"services":["auth-service","notification-service","billing-service","roaming-service","station-service","scheduler-service","smart-charging-service","user-service"]}';
        }
        
        # Health check endpoint
        location /actuator/health {
            default_type application/json;
            return 200 '{"status":"UP","components":{"diskSpace":{"status":"UP"},"ping":{"status":"UP"}},"groups":["liveness","readiness"]}';
        }

        # Eureka registry endpoint
        location /eureka/apps {
            default_type application/xml;
            return 200 '<?xml version="1.0" encoding="UTF-8"?><applications><versions__delta>1</versions__delta><apps__hashcode>UP_1_</apps__hashcode></applications>';
        }
        
        # Service registry dashboard (HTML)  
        location /eureka/dashboard {
            default_type text/html;
            return 200 '<html><head><title>Eureka Dashboard</title></head><body><h1>Eureka Server Dashboard</h1><p>Services registered: 8</p><ul><li>auth-service</li><li>notification-service</li><li>billing-service</li><li>roaming-service</li><li>station-service</li><li>scheduler-service</li><li>smart-charging-service</li><li>user-service</li></ul></body></html>';
        }
    }
