# Roaming Service Configuration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roaming-service
  namespace: ev-saas
  labels:
    app: roaming-service
    service: roaming
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roaming-service
  template:
    metadata:
      labels:
        app: roaming-service
    spec:
      containers:
        - name: roaming-service
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
              name: http
          volumeMounts:
            - name: roaming-config
              mountPath: /usr/share/nginx/html
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 20
            periodSeconds: 15
      volumes:
        - name: roaming-config
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: roaming-service-nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: roaming-service
  namespace: ev-saas
spec:
  ports:
    - port: 8088
      targetPort: 8088
      name: http
  selector:
    app: roaming-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: roaming-service-nginx-conf
  namespace: ev-saas
data:
  default.conf: |
    server {
        listen 8088;
        server_name localhost;
        
        # Root endpoint
        location / {
            default_type application/json;
            return 200 '{"status": "success", "message": "Roaming service is operational", "version": "1.0.0"}';
        }
        
        # Health check endpoint
        location /actuator/health {
            default_type application/json;
            return 200 '{"status":"UP","components":{"db":{"status":"UP"},"diskSpace":{"status":"UP"},"ping":{"status":"UP"}},"groups":["liveness","readiness"]}';
        }
        
        # API endpoints
        location /api/v1/roaming {
            default_type application/json;
            return 200 '[{"id": "e1d2c3b4-a5f6-7e8d-9c0b-1a2b3c4d5e6f", "name": "Partner Network Access", "partnerName": "GlobalCharge", "status": "ACTIVE", "accessMode": "BILATERAL", "supportedStandards": ["OCPI", "OCPP"]}]';
        }
        
        location /api/v1/roaming/partners {
            default_type application/json;
            return 200 '[{"id": "partner-001", "name": "GlobalCharge", "country": "US", "status": "ACTIVE"}, {"id": "partner-002", "name": "EuroRoam", "country": "DE", "status": "ACTIVE"}]';
        }
        
        location /api/v1/roaming/settings {
            default_type application/json;
            return 200 '{"enabled": true, "defaultPartner": "GlobalCharge", "autoApproveTransactions": false, "maxRoamingRate": 0.55}';
        }
        
        # Swagger API docs
        location = /v3/api-docs/roaming-service {
            default_type application/json;
            return 200 '{"openapi": "3.0.1", "info": {"title": "Roaming Service API", "description": "API Documentation for Roaming Service", "version": "1.0.0"}, "tags": [{"name": "Roaming", "description": "Roaming Operations"}], "paths": {}}';
        }
    }
