# Smart Charging Service Configuration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-charging-service
  namespace: ev-saas
  labels:
    app: smart-charging-service
    service: smart-charging
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-charging-service
  template:
    metadata:
      labels:
        app: smart-charging-service
    spec:
      containers:
        - name: smart-charging-service
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
              name: http
          volumeMounts:
            - name: smart-charging-config
              mountPath: /usr/share/nginx/html
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8086
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8086
            initialDelaySeconds: 20
            periodSeconds: 15
      volumes:
        - name: smart-charging-config
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: smart-charging-service-nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: smart-charging-service
  namespace: ev-saas
spec:
  ports:
    - port: 8086
      targetPort: 8086
      name: http
  selector:
    app: smart-charging-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-charging-service-nginx-conf
  namespace: ev-saas
data:
  default.conf: |
    server {
        listen 8086;
        server_name localhost;
        
        # Root endpoint
        location / {
            default_type application/json;
            return 200 '{"status": "success", "message": "Smart Charging service running in temporary mode", "version": "1.0.0"}';
        }
        
        # Health check endpoint
        location /actuator/health {
            default_type application/json;
            return 200 '{"status":"UP","components":{"db":{"status":"UP"},"diskSpace":{"status":"UP"},"ping":{"status":"UP"}},"groups":["liveness","readiness"]}';
        }
        
        # API endpoints
        location /api/v1/smart-charging {
            default_type application/json;
            return 200 '[{"id": "a3b4c5d6-e7f8-9a0b-1c2d-3e4f5a6b7c8d", "name": "Smart Charging Schedule", "algorithm": "OPTIMAL_LOAD_DISTRIBUTION", "status": "ACTIVE", "stationIds": ["fc5a81b3-4dad-4c7e-b8f3-0c9c2746be22"]}]';
        }
        
        location /api/v1/smart-charging/algorithms {
            default_type application/json;
            return 200 '[{"id": "OPTIMAL_LOAD_DISTRIBUTION", "name": "Optimal Load Distribution", "description": "Balances load across all charging stations"}, {"id": "PRICE_OPTIMIZED", "name": "Price Optimized", "description": "Optimizes charging based on electricity prices"}]';
        }
        
        location /api/v1/smart-charging/settings {
            default_type application/json;
            return 200 '{"enabled": true, "defaultAlgorithm": "OPTIMAL_LOAD_DISTRIBUTION", "maxPowerDraw": 300, "useGridConstraints": true}';
        }
        
        # Swagger API docs
        location = /v3/api-docs/smart-charging-service {
            default_type application/json;
            return 200 '{"openapi": "3.0.1", "info": {"title": "Smart Charging Service API", "description": "API Documentation for Smart Charging Service", "version": "1.0.0"}, "tags": [{"name": "Smart Charging", "description": "Smart Charging Operations"}], "paths": {}}';
        }
    }
