apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-configmap.yaml
  - 02-secrets.yaml
  - 03-postgres.yaml
  - 04-redis.yaml
  - 05-api-gateway.yaml
  - 06-service-deployments.yaml
  - nginx.yaml
  - cloudflare-tunnel.yaml

namespace: ev-saas

commonLabels:
  app.kubernetes.io/part-of: ev-saas-platform

patchesStrategicMerge:
  # Add any patches here if needed 