apiVersion: v1
kind: Namespace
metadata:
  name: ev-saas
---
# Auth Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: ev-saas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: ev-saas-platform-auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres.ev-infra.svc.cluster.local:5432/evsaas_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "evsaas"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "evsaas_password"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ev-saas
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: auth-service
---
# Notification Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: ev-saas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: ev-saas-platform-notification-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8087
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres.ev-infra.svc.cluster.local:5432/notification_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "evsaas"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "evsaas_password"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.ev-infra.svc.cluster.local:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: ev-saas
spec:
  ports:
    - port: 8087
      targetPort: 8087
  selector:
    app: notification-service
---
# Roaming Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roaming-service
  namespace: ev-saas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roaming-service
  template:
    metadata:
      labels:
        app: roaming-service
    spec:
      containers:
        - name: roaming-service
          image: ev-saas-platform-roaming-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8088
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres.ev-infra.svc.cluster.local:5432/evsaas_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "evsaas"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "evsaas_password"
---
apiVersion: v1
kind: Service
metadata:
  name: roaming-service
  namespace: ev-saas
spec:
  ports:
    - port: 8088
      targetPort: 8088
  selector:
    app: roaming-service
