apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false

  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: evsaas_db
    user: evsaas
    secureJsonData:
      password: evsaas_password
    jsonData:
      sslmode: "disable"
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1400

  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    database: evsaas_timeseries_db
    user: evsaas
    secureJsonData:
      password: evsaas_password
    jsonData:
      sslmode: "disable"
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: true 