# Cloudflare Tunnel configuration
# This file will be populated after tunnel creation

tunnel: 81810f9b-15e9-4579-8ab8-8f4e7b7c9c68
credentials-file: /etc/cloudflared/credentials.json

# Log level can be one of: debug, info, warn, error, fatal
loglevel: info

# Ingress rules determine which traffic should go where
ingress:
  # Main web service via nginx gateway
  - hostname: api.nbevc.com
    service: http://nginx:80
  
  # Admin portal direct access
  - hostname: console.nbevc.com
    service: http://admin-portal:3000

  # API Gateway direct access
  # - hostname: api.nbevc.com
    # service: http://api-gateway:8082
  
  # Auth service direct access
  - hostname: auth.nbevc.com
    service: http://auth-service:8081
  
  # Keycloak admin access
  - hostname: keycloak.nbevc.com
    service: http://keycloak:8080
    originRequest:
      connectTimeout: 30s
  
  # Monitoring services
  - hostname: prometheus.nbevc.com
    service: http://prometheus:9090
  
  - hostname: grafana.nbevc.com
    service: http://grafana:3000
  
  - hostname: mailhog.nbevc.com
    service: http://mailhog:8025
  
  # Catch-all rule (required)
  - service: http_status:404 